version: '3.3'

services:
  landing-service:
    build: ./landing 
    hostname: landing-service
    ports:
      - 5050:5050
    networks:
      sample:
        aliases:
          - landing-service
  addition-service:
    build: ./addition
    hostname: addition-service
    ports:
      - 5051:5051
    networks:
      sample:
        aliases:
          - addition-service
  subtraction-service:
    build: ./subtraction
    hostname: subtraction-service
    ports:
      - 5052:5052
    networks:
      sample:
        aliases:
          - subtraction-service
  multiplication-service:
    build: ./multiplication
    hostname: multiplication-service
    ports:
      - 5053:5053
    networks:
      sample:
        aliases:
          - multiplication-service
  division-service:
    build: ./division
    hostname: division-service
    ports:
      - 5054:5054
    networks:
      sample:
        aliases:
          - division-service
  modulo-service:
    build: ./modulo
    hostname: modulo-service
    ports:
      - 5055:5055
    networks:
      sample:
        aliases:
          - modulo-service
  exponent-service:
    build: ./exponent
    hostname: exponent-service
    ports:
      - 5056:5056
    networks:
      sample:
        aliases:
          - exponent-service
  gcd-service:
    build: ./gcd
    hostname: gcd-service
    ports:
      - 5057:5057
    networks:
      sample:
        aliases:
          - gcd-service
networks:
  sample: